### PR TITLE
Set downloaded file name with `Content-Disposition` header.

### PR DESCRIPTION
**Pull request by iurisilvio**

### CODE REVIEW

**Comment by iurisilvio** [comment]
It breaks with unicode characters. I'm investigating the issue. It is not good to merge yet.

**Comment by iurisilvio** [comment]
HTTP headers does not support unicode chars. The best way to fix this is sanitizing filename on file create.

**Comment by iurisilvio** [comment]
I fixed the unicode issue in my upload field. I created a custom `UploadedField` to fix my problem, sanitizing the filename with `werkzeug.secure_filename`. I'm using Flask, so `werkzeug` is already a dependency for me.

```
from depot.fields.sqlalchemy import UploadedFile, UploadedFileField
from werkzeug import secure_filename

class SafeUploadedFile(UploadedFile):
    def process_content(self, content, filename=None, content_type=None):
        if not filename:
            filename = content.filename
        filename = secure_filename(filename)
        super(SafeUploadedFile, self).process_content(content, filename, content_type)


# my model attribute
myfile = db.Column(UploadedFileField(upload_type=SafeUploadedFile))
```

You must sanitize filenames. It is a common attack vector. Maybe depot can do it built-in.

**Comment by amol-** [comment]
On depot itself the filename cannot be used as an attack vector as the filename is only stored as metadata and never used to actually read/write the file. That is one of the reasons why depot uses a self generated id for files instead of the name.

**Comment by amol-** [comment]
https://github.com/amol-/depot/commit/ba582d90145fe2097755a727f800a28254446a0c should provide a  proper management of Content-Disposition with support for unicode file names

**Comment by iurisilvio** [comment]
Really thanks! Can you push a new version with this change to PyPI? For now, I'm using it from github.

**Pull request closed without merging**
