### PR TITLE
Add support for S3 StorageClass.  Fixes #56

### LINKED ISSUE #56: Add support for S3 StorageClass
We need to have an ability to select different storage class, per https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html (e.g. INTELLIGENT_TIERING).  S3 pricing is vastly different based on storage class.

### PR DESCRIPTION
**Pull request by johnvencky**
Add support for S3 StorageClass.  Fixes #56

### CODE REVIEW

**Comment by amol-** [comment]
Looks good to me, would you mind adding a test to verify that when you specify a storage class that it actually used?

**Comment by ghost** [comment]
> Looks good to me, would you mind adding a test to verify that when you specify a storage class that it actually used?

Hey!  Sorry for the delay -- it took me awhile to set up a proper test environment. :)  Added a test to verify that when we upload 'STANDARD_IA', we get back the object of class 'STANDARD_IA'.  Please take another look.

Also Alessandro, I wanted to ask about how often you create a release;  it looks like last commit was back in January and no release is being planned soon?  We are launching our project in September and I was wondering if S3 class support will be available;  or should we plan to roll our own version of filedepot.

Thanks!

**Comment by amol-** [comment]
Thanks! Really appreciated this!
I'll try to release this in the next few days.

**Comment by amol-** [comment]
0.7.0 released with support for storage class

**Pull request merged**
